---
title: "u.gg webscraping"
author: "Bram van Smoorenburg"
date: "27 November 2019"
output: html_document
---

https://u.gg/lol/tier-list/?role=support&queueType=normal_blind_5x5

```{r}
library(rvest)
library(parallel)
```

```{r}
ncores=6
```

split vector
```{r}
splitvec=function(vec,n) {
  if (length(vec)<n) {
    stop("vector not long enough, length:",length(vec))
  }
  out=round(seq(0,length(vec),length.out = n+1))
  return(lapply(2:(n+1),function(y){vec[(out[y-1]+1):out[y]]}))
}
```

champion list
```{r}
namelist=c("aatrox","ahri","akali","alistar","amumu","anivia","annie","aphelios","ashe","aurelionsol","azir","bard","blitzcrank","brand","braum","caitlyn","camille","cassiopeia","chogath","corki","darius","diana","drmundo","draven","ekko","elise","evelynn","ezreal","fiddlesticks","fiora","fizz","galio","gangplank","garen","gnar","gragas","graves","hecarim","heimerdinger","illaoi","irelia","ivern","janna","jarvaniv","jax","jayce","jhin","jinx","kaisa","kalista","karma","karthus","kassadin","katarina","kayle","kayn","kennen","khazix","kindred","kled","kogmaw","leblanc","leesin","leona","lissandra","lucian","lulu","lux","malphite","malzahar","maokai","masteryi","missfortune","mordekaiser","morgana","nami","nasus","nautilus","neeko","nidalee","nocturne","nunu","olaf","orianna","ornn","pantheon","poppy","pyke","qiyana","quinn","rakan","rammus","reksai","renekton","rengar","riven","rumble","ryze","sejuani","senna","sett","shaco","shen","shyvana","singed","sion","sivir","skarner","sona","soraka","swain","sylas","syndra","tahmkench","taliyah","talon","taric","teemo","thresh","tristana","trundle","tryndamere","twistedfate","twitch","udyr","urgot","varus","vayne","veigar","velkoz","vi","viktor","vladimir","volibear","warwick","wukong","xayah","xerath","xinzhao","yasuo","yorick","yuumi","zac","zed","ziggs","zilean","zoe","zyra")
splnames=splitvec(namelist,ncores)
```

function
```{r}
uggfunc=function(namevec) {
  library(rvest)
  champtabl=data.frame(name=NA,topbplayrate=NA,jglbplayrate=NA,midbplayrate=NA,botbplayrate=NA,supbplayrate=NA,topbwinrate=NA,jglbwinrate=NA,midbwinrate=NA,botbwinrate=NA,supbwinrate=NA,toprplayrate=NA,jglrplayrate=NA,midrplayrate=NA,botrplayrate=NA,suprplayrate=NA,toprwinrate=NA,jglrwinrate=NA,midrwinrate=NA,botrwinrate=NA,suprwinrate=NA)[-1,]
  for (i in namevec) {
    url=paste0("https://u.gg/lol/champions/",i,"/build/?queueType=normal_blind_5x5",collapse="") #?queueType=normal_blind_5x5
    page=try(read_html(url,encoding = "ISO-8859-1"))
    for (a in 1:10) {
      if (class(page)[1]!="try-error") {
        break
      }
      Sys.sleep(1)
      page=try(read_html(url,encoding = "ISO-8859-1"))
    }
    page2=html_text(page)
    roles=strsplit(page2,"world_overall_")[[1]][7:11] #world_silver_ or overall_
    roles=roles[c(4,1,5,3,2)]
    
    corebuild=lapply(roles,function(x){strsplit(x,"rec_skills")[[1]][1]})
corebuild=lapply(corebuild,function(x){strsplit(x,"rec_core_items")[[1]][2]})
corebuild=lapply(corebuild,function(x){strsplit(x,"\"matches\":")[[1]][2]})
cb1=as.numeric(lapply(corebuild,function(x){strsplit(x,",")[[1]][1]}))
cb2=lapply(corebuild,function(x){strsplit(x,"win_rate\":")[[1]][2]})
cb2=as.numeric(lapply(cb2,function(x){strsplit(x,",")[[1]][1]}))

runes=lapply(roles,function(x){strsplit(x,"active_perks")[[1]][1]})
runes=lapply(runes,function(x){strsplit(x,"rec_runes")[[1]][2]})
runes=lapply(runes,function(x){strsplit(x,"\"matches\":")[[1]][2]})
r1=as.numeric(lapply(runes,function(x){strsplit(x,",")[[1]][1]}))
r2=lapply(runes,function(x){strsplit(x,"win_rate\":")[[1]][2]})
r2=as.numeric(lapply(r2,function(x){strsplit(x,",")[[1]][1]}))

champtabl=rbind(champtabl,c(NA,cb1,cb2,r1,r2))
champtabl[nrow(champtabl),1]=i
  }
  colnames(champtabl)=c("names","topiplayrate","jgliplayrate","midiplayrate","botiplayrate","supiplayrate","topiwinrate","jgliwinrate","midiwinrate","botiwinrate","supiwinrate","toprplayrate","jglrplayrate","midrplayrate","botrplayrate","suprplayrate","toprwinrate","jglrwinrate","midrwinrate","botrwinrate","suprwinrate")
rownames(champtabl)=champtabl[,1]
champtabl=champtabl[,-1]
return(champtabl)
}
```

running function
```{r}
clu=makeCluster(ncores)
tabl=parLapply(clu,splnames,uggfunc)
stopCluster(clu)
tabl=do.call(rbind,tabl)
apply(tabl[,1:5],2,function(x){sort(na.omit(x))[round(0.8*sum(!is.na(x)))]})
```

role tables
```{r}
threshold=1e3
itabltop=tabl[!is.na(tabl$topiplayrate)&tabl$topiplayrate>=threshold,]
itabljgl=tabl[!is.na(tabl$jgliplayrate)&tabl$jgliplayrate>=threshold,]
itablmid=tabl[!is.na(tabl$midiplayrate)&tabl$midiplayrate>=threshold,]
itablbot=tabl[!is.na(tabl$botiplayrate)&tabl$botiplayrate>=threshold,]
itablsup=tabl[!is.na(tabl$supiplayrate)&tabl$supiplayrate>=threshold,]

rtabltop=tabl[!is.na(tabl$toprplayrate)&tabl$toprplayrate>=threshold,]
rtabljgl=tabl[!is.na(tabl$jglrplayrate)&tabl$jglrplayrate>=threshold,]
rtablmid=tabl[!is.na(tabl$midrplayrate)&tabl$midrplayrate>=threshold,]
rtablbot=tabl[!is.na(tabl$botrplayrate)&tabl$botrplayrate>=threshold,]
rtablsup=tabl[!is.na(tabl$suprplayrate)&tabl$suprplayrate>=threshold,]
```

```{r}
c(max(rtabltop[,16],na.rm = TRUE),max(rtabljgl[,17],na.rm = TRUE),max(rtablmid[,18],na.rm = TRUE),max(rtablbot[,19],na.rm = TRUE),max(rtablsup[,20],na.rm = TRUE))
gc()
```
